Search space (old=query nodes; new=agent action space):
old: ['Index Only Scan' 'Index Scan' 'Seq Scan'] ['Hash Join' 'Nested Loop'] ['Hash' 'Hash Join' 'Index Only Scan' 'Index Scan' 'Memoize' 'Nested Loop'
 'Seq Scan' 'SimpleAggregate']
new: ['Index Only Scan' 'Index Scan' 'Seq Scan'] ['Hash Join' 'Merge Join' 'Nested Loop'] ['Hash' 'Hash Join' 'Index Only Scan' 'Index Scan' 'Memoize' 'Nested Loop'
 'Seq Scan' 'SimpleAggregate']
28c
28c
28c
28c
28c
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35348)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35356)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35362)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35374)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35378)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35382)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35384)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35400)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35404)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35412)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35418)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35424)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35436)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35440)
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 269, in handle
    if self.handle_json(json.loads(json_msg)):
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 285, in handle_json
    result = self.server.leon_model.predict_plan(self.__messages)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 195, in predict_plan
    "analysis_time": self.analysis_all_time / self.n,
ZeroDivisionError: division by zero
----------------------------------------
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
28c
Process Process-1:
Traceback (most recent call last):
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/wyz/online/LEONForPostgres/leon_server.py", line 307, in start_server
    server.serve_forever()
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/data1/wyz/miniconda3/envs/unlearning/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
